# Generated by Django 5.0.6 on 2025-01-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_verificationcode_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='delete_at',
            field=models.DateTimeField(null=True),
        ),
    ]
