# Generated by Django 5.0.6 on 2024-08-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dateRegistration',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
    ]
