# Generated by Django 5.0.6 on 2024-08-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_remove_user_dateregistration_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='default.svg', max_length=20),
        ),
    ]
