# Generated by Django 5.0.6 on 2024-09-17 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 17, 16, 17, 32, 503236, tzinfo=datetime.timezone.utc)),
        ),
    ]
