# Generated by Django 5.0.6 on 2024-09-21 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_news_alter_user_last_activity_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='to',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 19, 53, 53, 564758, tzinfo=datetime.timezone.utc)),
        ),
    ]
