# Generated by Django 5.0.6 on 2024-09-21 21:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_remove_subscription_to_alter_user_last_activity'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='choice',
        ),
        migrations.AddField(
            model_name='subscription',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='object_id',
            field=models.PositiveIntegerField(default=123456),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='tag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
