# Generated by Django 5.0.6 on 2024-12-30 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0012_user_activated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
