# Generated by Django 5.0.6 on 2024-12-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0013_delete_verificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activated',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
