# Generated by Django 5.0.6 on 2025-01-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0016_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
